.TH "PanoCV" 1 "06 Apr 2020" 0.20200406 "User Manual"

.SH NAME
panocv

.SH DESCRIPTION
The code given here is for simple image stitching of images using OpenCV.

.SH SYNOPSIS
\fBpanocv\fI <img_result> <img_file_1> <img_file_2> ...\fR

.SH EXAMPLE
\fBpanocv\fR result.jpg image1.jpg image2.jpg

.SH COPYRIGHT
Public Domain Mark 1.0
 No Copyright

.SH SEE ALSO
 hugin(1),
 PTmender(),
 ale(1),
 autopano(1),
 panostart(1)

.SH CONTACTS
 Homepage: https://github.com/ImageProcessing-ElectronicPublications/panocv
 Email: zvezdochiot@users.sourceforge.net
